version: "3"
services:
  frontend:
    build: 
      context: ./Client
      args:
        VITE_API_URL: "http://localhost:3000"
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./Server
      args:
        CLIENT_URL: "http://localhost:80"
    ports:
      - "3000:3000"
    volumes:
      - ./Server/database.sqlite:/app/database.sqlite # Mantieni persistente il database SQLite
