import { Immobile } from "../models/ImmobileT"

export const Immobili : Immobile[] = [
    {
        title: "Villa sul mare",
        street: "Via dei mille",
        size: "40",
        bathroom_number: "2",
        local_number: "3",
        agent_image: "https://informatica.dieti.unina.it/images/foto-docenti/di-martino.png",
        price: "400.000€",
        images: ["https://cdn.pixabay.com/photo/2016/11/18/17/46/house-1836070_1280.jpg", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxG8ihFgvtyxCvoVxgoVKto6MpkCZzVwNoxA&s"],
        lat: 40.826232,
        lon: 14.186043,
    },
    {
        title: "Casa raccomandabile",
        street: "Via delle truffe",
        size: "12",
        bathroom_number: "0",
        local_number: "1/2",
        agent_image: "https://static8.depositphotos.com/1206957/800/i/450/depositphotos_8002210-stock-photo-masked-man.jpg",
        price: "800.000€",
        images: ["https://preview.redd.it/you-guys-ever-completely-gutted-a-bathroom-from-a-year-1900-v0-24crbmeg1slc1.jpg?width=640&crop=smart&auto=webp&s=f028f3e1cd6c9c14fff30eca5bc2fa32e5f16aea", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxG8ihFgvtyxCvoVxgoVKto6MpkCZzVwNoxA&s"],
        lat: 40.828602,
        lon: 14.198037,
    },
    {
        title: "Casetta in campagna 1",
        street: "Reggia di Caserta",
        size: "1000",
        bathroom_number: "20",
        local_number: "70",
        agent_image: "https://www.reggiadicasertaunofficial.it/wp-content/uploads/reggia-di-caserta-carlo-iii-di-borbone-ritratto-da-capodimonte-1300x1300.webp",
        price: "100.000€",
        images: ["https://lh6.googleusercontent.com/proxy/RXfj4LDtn7V0NEzjtbW-ZTgrOZcy6fDTIPrjk_-V-dnauGAW09EVWOgu4UUDI2HnlKF9rb8p1en4dK4casMO_PJUbdWuLMgJ8lMhgiRmTEnnTJKvMevICILm"],
        lat: 40.827634,
        lon: 14.171069,
    },
    {
        title: "Casetta in campagna 2",
        street: "Reggia di Caserta",
        size: "1000",
        bathroom_number: "20",
        local_number: "70",
        agent_image: "https://www.reggiadicasertaunofficial.it/wp-content/uploads/reggia-di-caserta-carlo-iii-di-borbone-ritratto-da-capodimonte-1300x1300.webp",
        price: "100.000€",
        images: ["https://lh6.googleusercontent.com/proxy/RXfj4LDtn7V0NEzjtbW-ZTgrOZcy6fDTIPrjk_-V-dnauGAW09EVWOgu4UUDI2HnlKF9rb8p1en4dK4casMO_PJUbdWuLMgJ8lMhgiRmTEnnTJKvMevICILm"],
        lat: 40.823324,
        lon: 14.173329,
    },
    {
        title: "Casetta in campagna 3",
        street: "Reggia di Caserta",
        size: "1000",
        bathroom_number: "20",
        local_number: "70",
        agent_image: "https://www.reggiadicasertaunofficial.it/wp-content/uploads/reggia-di-caserta-carlo-iii-di-borbone-ritratto-da-capodimonte-1300x1300.webp",
        price: "100.000€",
        images: ["https://lh6.googleusercontent.com/proxy/RXfj4LDtn7V0NEzjtbW-ZTgrOZcy6fDTIPrjk_-V-dnauGAW09EVWOgu4UUDI2HnlKF9rb8p1en4dK4casMO_PJUbdWuLMgJ8lMhgiRmTEnnTJKvMevICILm"],
        lat: 40.823634,
        lon: 15.179069,
    },
    {
        title: "Casetta in campagna 4",
        street: "Reggia di Caserta",
        size: "1000",
        bathroom_number: "20",
        local_number: "70",
        agent_image: "https://www.reggiadicasertaunofficial.it/wp-content/uploads/reggia-di-caserta-carlo-iii-di-borbone-ritratto-da-capodimonte-1300x1300.webp",
        price: "100.000€",
        images: ["https://lh6.googleusercontent.com/proxy/RXfj4LDtn7V0NEzjtbW-ZTgrOZcy6fDTIPrjk_-V-dnauGAW09EVWOgu4UUDI2HnlKF9rb8p1en4dK4casMO_PJUbdWuLMgJ8lMhgiRmTEnnTJKvMevICILm"],
        lat: 40.811634,
        lon: 14.172069,
    }
]