// import { Immobile } from "../models/ImmobileT";

// export const Immobili : Immobile[] = [
//     {
//         title: "Villa sul mare",
//         street: "Via dei mille",
//         size: "40",
//         bathrooms: "2",
//         locals: "3",
//         agentImage: "https://informatica.dieti.unina.it/images/foto-docenti/di-martino.png",
//         price: "400.000",
//         images: ["https://cdn.pixabay.com/photo/2016/11/18/17/46/house-1836070_1280.jpg", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxG8ihFgvtyxCvoVxgoVKto6MpkCZzVwNoxA&s"],
//         lat: 40.826232,
//         lon: 14.186043,
//     },
//     {
//         title: "Casa raccomandabile",
//         street: "Via delle truffe",
//         size: "12",
//         bathrooms: "0",
//         locals: "1/2",
//         agentImage: "https://static8.depositphotos.com/1206957/800/i/450/depositphotos_8002210-stock-photo-masked-man.jpg",
//         price: "800.000",
//         images: ["https://preview.redd.it/you-guys-ever-completely-gutted-a-bathroom-from-a-year-1900-v0-24crbmeg1slc1.jpg?width=640&crop=smart&auto=webp&s=f028f3e1cd6c9c14fff30eca5bc2fa32e5f16aea", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxG8ihFgvtyxCvoVxgoVKto6MpkCZzVwNoxA&s"],
//         lat: 40.828602,
//         lon: 14.198037,
//     },
//     {
//         title: "Casetta in campagna 1",
//         street: "Reggia di Caserta",
//         size: "1000",
//         bathrooms: "20",
//         locals: "70",
//         agentImage: "https://www.reggiadicasertaunofficial.it/wp-content/uploads/reggia-di-caserta-carlo-iii-di-borbone-ritratto-da-capodimonte-1300x1300.webp",
//         price: "100.000",
//         images: ["https://lh6.googleusercontent.com/proxy/RXfj4LDtn7V0NEzjtbW-ZTgrOZcy6fDTIPrjk_-V-dnauGAW09EVWOgu4UUDI2HnlKF9rb8p1en4dK4casMO_PJUbdWuLMgJ8lMhgiRmTEnnTJKvMevICILm"],
//         lat: 40.827634,
//         lon: 14.171069,
//     },
//     {
//         title: "Casetta in campagna 2",
//         street: "Reggia di Caserta",
//         size: "1000",
//         bathrooms: "20",
//         locals: "70",
//         agentImage: "https://www.reggiadicasertaunofficial.it/wp-content/uploads/reggia-di-caserta-carlo-iii-di-borbone-ritratto-da-capodimonte-1300x1300.webp",
//         price: "100.000",
//         images: ["https://lh6.googleusercontent.com/proxy/RXfj4LDtn7V0NEzjtbW-ZTgrOZcy6fDTIPrjk_-V-dnauGAW09EVWOgu4UUDI2HnlKF9rb8p1en4dK4casMO_PJUbdWuLMgJ8lMhgiRmTEnnTJKvMevICILm"],
//         lat: 40.823324,
//         lon: 14.173329,
//     },
//     {
//         title: "Casetta in campagna 3",
//         street: "Reggia di Caserta",
//         size: "1000",
//         bathrooms: "20",
//         locals: "70",
//         agentImage: "https://www.reggiadicasertaunofficial.it/wp-content/uploads/reggia-di-caserta-carlo-iii-di-borbone-ritratto-da-capodimonte-1300x1300.webp",
//         price: "100.000",
//         images: ["https://lh6.googleusercontent.com/proxy/RXfj4LDtn7V0NEzjtbW-ZTgrOZcy6fDTIPrjk_-V-dnauGAW09EVWOgu4UUDI2HnlKF9rb8p1en4dK4casMO_PJUbdWuLMgJ8lMhgiRmTEnnTJKvMevICILm"],
//         lat: 40.823634,
//         lon: 15.179069,
//     },
//     {
//         title: "Casetta in campagna 4",
//         street: "Reggia di Caserta",
//         size: "1000",
//         bathrooms: "20",
//         locals: "70",
//         agentImage: "https://www.reggiadicasertaunofficial.it/wp-content/uploads/reggia-di-caserta-carlo-iii-di-borbone-ritratto-da-capodimonte-1300x1300.webp",
//         price: "100.000",
//         images: ["https://lh6.googleusercontent.com/proxy/RXfj4LDtn7V0NEzjtbW-ZTgrOZcy6fDTIPrjk_-V-dnauGAW09EVWOgu4UUDI2HnlKF9rb8p1en4dK4casMO_PJUbdWuLMgJ8lMhgiRmTEnnTJKvMevICILm"],
//         lat: 40.811634,
//         lon: 14.172069,
//     },
//     {
//       "title": "Appartamento moderno",
//       "street": "Via Vittorio Veneto",
//       "size": "70",
//       "bathrooms": "1",
//       "locals": "2",
//       "agentImage": "https://informatica.dieti.unina.it/images/foto-docenti/difonso.png",
//       "price": "250.000",
//       "images": ["https://www.fratellipellizzari.it/files/styles/zoom/public/images/case-moderne-vicenza-verona.jpg?itok=6T9Ykqa6"],
//       "lat": 41.902783,
//       "lon": 12.496365
//     },
//     {
//       "title": "Monolocale accogliente",
//       "street": "Corso Garibaldi",
//       "size": "30",
//       "bathrooms": "1",
//       "locals": "1",
//       "agentImage": "https://informatica.dieti.unina.it/images/foto-docenti/dipaola.png",
//       "price": "150.000",
//       "images": ["https://www.pozzicase.it/sites/default/files/styles/immagine_wide_blocco_a/public/casa/main.jpg?itok=jVvRVwpp"],
//       "lat": 45.464203,
//       "lon": 9.189982
//     },
//     {
//       "title": "Attico di lusso",
//       "street": "Via Roma",
//       "size": "120",
//       "bathrooms": "3",
//       "locals": "5",
//       "agentImage": "https://informatica.dieti.unina.it/images/foto-docenti/santarcangelo.png",
//       "price": "1.200.000",
//       "images": ["https://www.costruirebio.it/wp-content/uploads/AdobeStock_297606677-scaled.jpeg"],
//       "lat": 41.117143,
//       "lon": 16.871871
//     },
//     {
//       "title": "Casa di campagna",
//       "street": "Via delle Rose",
//       "size": "85",
//       "bathrooms": "2",
//       "locals": "4",
//       "agentImage": "https://informatica.dieti.unina.it/images/foto-docenti/dicostanzo.png",
//       "price": "300.000",
//       "images": ["https://www.costantinilegno.it/wp-content/uploads/2017/04/LACOST-Casa-in-legno-Narni-Terni_10.jpg"],
//       "lat": 45.071312,
//       "lon": 7.686856
//     },
//     {
//       "title": "Villetta bifamiliare",
//       "street": "Via delle Acacie",
//       "size": "90",
//       "bathrooms": "2",
//       "locals": "4",
//       "agentImage": "https://informatica.dieti.unina.it/images/foto-docenti/ferrucci.png",
//       "price": "450.000",
//       "images": ["https://www.costruirebio.it/wp-content/uploads/casa-moderna-2-1.jpg"],
//       "lat": 41.900783,
//       "lon": 12.496365
//     },
//     {
//       "title": "Appartamento economico",
//       "street": "Via dei Tulipani",
//       "size": "50",
//       "bathrooms": "1",
//       "locals": "2",
//       "agentImage": "https://informatica.dieti.unina.it/images/foto-docenti/mazzeo.png",
//       "price": "120.000",
//       "images": ["https://www.pineca.it/media/cache/avp_product_thumbnail/7/6/f/b/76fbc5ad9f4b968b14e0637003772b5c655203f8_600x435.jpg"],
//       "lat": 45.463203,
//       "lon": 9.189982
//     },
//     {
//       "title": "Casa indipendente",
//       "street": "Via del Sole",
//       "size": "100",
//       "bathrooms": "2",
//       "locals": "4",
//       "agentImage": "https://informatica.dieti.unina.it/images/foto-docenti/sorce.png",
//       "price": "500.000",
//       "images": [],
//       "lat": 41.112343,
//       "lon": 16.871871
//     },
//     {
//       "title": "Rustico in collina",
//       "street": "Via della Quiete",
//       "size": "150",
//       "bathrooms": "3",
//       "locals": "6",
//       "agentImage": "https://informatica.dieti.unina.it/images/foto-docenti/tripicchio.png",
//       "price": "600.000",
//       "images": ["https://www.norgeshus.it/wp-content/uploads/showcase/prefabricated-houses/casa-prefabbricata-150.jpg"],
//       "lat": 45.073312,
//       "lon": 7.684456
//     },
//     {
//       "title": "Appartamento con giardino",
//       "street": "Via delle Gardenie",
//       "size": "80",
//       "bathrooms": "2",
//       "locals": "3",
//       "agentImage": "https://informatica.dieti.unina.it/images/foto-docenti/viscusi.png",
//       "price": "320.000",
//       "images": ["https://images.homify.com/v1448129217/p/photo/image/1135013/7.jpg"],
//       "lat": 40.826232,
//       "lon": 14.183323
//     },
//     {
//       "title": "Loft in centro",
//       "street": "Via Dante",
//       "size": "60",
//       "bathrooms": "1",
//       "locals": "2",
//       "agentImage": "https://informatica.dieti.unina.it/images/foto-docenti/aiello.png",
//       "price": "280.000",
//       "images": ["https://www.casa-naturale.com/wp-content/uploads/2021/04/cn-maggio-giugno2021-ritratto-casa-con-vista-02.jpg"],
//       "lat": 41.902993,
//       "lon": 12.496365
//     },
//     {
//       "title": "Villa con piscina",
//       "street": "Via dei Tigli",
//       "size": "200",
//       "bathrooms": "4",
//       "locals": "8",
//       "agentImage": "https://informatica.dieti.unina.it/images/foto-docenti/cimitile.png",
//       "price": "2.500.000",
//       "images": ["https://www.novellocaseinlegno.it/images/REALIZZAZIONI/VARESE-BERNARDI/Casa_prefabbricata_in_legno_Varese-top.jpg"],
//       "lat": 45.464293,
//       "lon": 9.189902
//     },
//     {
//       "title": "Appartamento panoramico",
//       "street": "Via del Panorama",
//       "size": "75",
//       "bathrooms": "2",
//       "locals": "3",
//       "agentImage": "https://informatica.dieti.unina.it/images/foto-docenti/musto.png",
//       "price": "400.000",
//       "images": ["https://www.easyservicesolutions.com/wp-content/uploads/2018/07/Case-moderne.jpg"],
//       "lat": 41.117213,
//       "lon": 16.871821
//     },
//     {
//       "title": "Casale storico",
//       "street": "Via del Centro Storico",
//       "size": "180",
//       "bathrooms": "3",
//       "locals": "6",
//       "agentImage": "https://informatica.dieti.unina.it/images/foto-docenti/penta.png",
//       "price": "1.800.000",
//       "images": ["https://caseprefabbricateinlegno.it/wp-content/uploads/casa-in-legno9.jpg"],
//       "lat": 45.070112,
//       "lon": 7.683326
//     },
//     {
//       "title": "Appartamento ristrutturato",
//       "street": "Via delle Margherite",
//       "size": "65",
//       "bathrooms": "1",
//       "locals": "2",
//       "agentImage": "https://informatica.dieti.unina.it/images/foto-docenti/picariello.png",
//       "price": "280.000",
//       "images": ["https://www.lignius.it/images/_processed_/6/6/csm_lignius_wolfhaus_berera_6333_2d23e2321c.jpg"],
//       "lat": 40.826322,
//       "lon": 14.186363
//     },
//     {
//       "title": "Villa di design",
//       "street": "Via dei Pini",
//       "size": "140",
//       "bathrooms": "3",
//       "locals": "5",
//       "agentImage": "https://informatica.dieti.unina.it/images/foto-docenti/sannino.png",
//       "price": "1.100.000",
//       "images": ["https://cdn.cosedicasa.com/wp-content/uploads/2013/06/check-up-casa.jpg"],
//       "lat": 41.909433,
//       "lon": 12.496305
//     },
//     {
//       "title": "Monolocale minimal",
//       "street": "Via dell'Arte",
//       "size": "35",
//       "bathrooms": "1",
//       "locals": "1",
//       "agentImage": "https://informatica.dieti.unina.it/images/foto-docenti/spagnuolo.png",
//       "price": "170.000",
//       "images": ["https://movieplayer.net-cdn.it/t/images/2024/05/02/pixar_up_jpg_1600x900_crop_q85.jpg"],
//       "lat": 45.464603,
//       "lon": 9.189102
//     },
//     {
//       "title": "Casa vista mare",
//       "street": "Via delle Onde",
//       "size": "90",
//       "bathrooms": "2",
//       "locals": "4",
//       "agentImage": "https://informatica.dieti.unina.it/images/foto-docenti/viscusi.png",
//       "price": "700.000",
//       "images": ["https://www.casabatllo.es/wp-content/uploads/2022/11/fachada-590x760-1.png"],
//       "lat": 41.117403,
//       "lon": 16.8718341
//     },
//     {
//       "title": "Appartamento luminoso",
//       "street": "Via della Luce",
//       "size": "70",
//       "bathrooms": "1",
//       "locals": "3",
//       "agentImage": "https://informatica.dieti.unina.it/images/foto-docenti/cipresso.png",
//       "price": "300.000",
//       "images": ["https://www.innovero.it/wp-content/uploads/2023/11/Casa-Ecologica.jpg"],
//       "lat": 45.070302,
//       "lon": 7.686116
//     },
//     {
//       "title": "Casa con terrazza",
//       "street": "Via della Pace",
//       "size": "85",
//       "bathrooms": "2",
//       "locals": "3",
//       "agentImage": "https://informatica.dieti.unina.it/images/foto-docenti/tortora.png",
//       "price": "500.000",
//       "images": ["https://upload.wikimedia.org/wikipedia/commons/a/af/Paolo_Monti_-_Servizio_fotografico_%28Italia%2C_1971%29_-_BEIC_6357716.jpg"],
//       "lat": 40.822232,
//       "lon": 14.18043
//     }
// ];