import { Immobile } from "../models/ImmobileT";

export const Immobili: any = [
    {
        title: "Appartamento Moderno",
        description: "Spazioso appartamento con vista panoramica, vicino ai principali servizi.",
        street: "Via Roma 15",
        size: 95,
        bathrooms: 2,
        locals: 4,
        price: 250000,
        efficienza: "A",
        type: "VENDITA",
        images: ["image1.jpg", "image2.jpg"],
        lat: 40.7128,
        lon: 74.0060,
        tags: ["panoramico", "moderno", "centrale"]
    },
    {
        title: "Villa con Giardino",
        description: "Lussuosa villa con giardino privato e piscina.",
        street: "Via delle Vigne 23",
        size: 350,
        bathrooms: 4,
        locals: 8,
        price: 1500000,
        efficienza: "B",
        type: "VENDITA",
        images: ["image3.jpg", "image4.jpg"],
        lat: 41.9028,
        lon: 12.4964,
        tags: ["lusso", "giardino", "piscina"]
    },
    {
        title: "Monolocale in Affitto",
        description: "Monolocale ideale per studenti, ben arredato e vicino alla stazione.",
        street: "Corso Italia 42",
        size: 40,
        bathrooms: 1,
        locals: 1,
        price: 500,
        efficienza: "C",
        type: "AFFITTO",
        images: ["image5.jpg"],
        lat: 45.4642,
        lon: 9.1900,
        tags: ["studenti", "arredato", "centrale"]
    },
    {
        title: "Appartamento con Terrazza",
        description: "Appartamento luminoso con una grande terrazza per cenare all'aperto.",
        street: "Via delle Rose 78",
        size: 120,
        bathrooms: 2,
        locals: 5,
        price: 350000,
        efficienza: "A",
        type: "VENDITA",
        images: ["image6.jpg", "image7.jpg"],
        lat: 43.7696,
        lon: 11.2558,
        tags: ["luminoso", "terrazza", "moderno"]
    },
    {
        title: "Casa con Vista Mare",
        description: "Affascinante casa con vista sul mare, perfetta per famiglie.",
        street: "Lungomare 4",
        size: 220,
        bathrooms: 3,
        locals: 6,
        price: 950000,
        efficienza: "A",
        type: "VENDITA",
        images: ["image8.jpg", "image9.jpg"],
        lat: 43.1073,
        lon: 9.9456,
        tags: ["vista mare", "familiare", "spaziosa"]
    },
    {
        title: "Attico con Solarium",
        description: "Elegante attico con solarium e vista sulla città.",
        street: "Piazza del Duomo 10",
        size: 150,
        bathrooms: 2,
        locals: 4,
        price: 800000,
        efficienza: "B",
        type: "VENDITA",
        images: ["image10.jpg", "image11.jpg"],
        lat: 45.4642,
        lon: 9.1900,
        tags: ["attico", "solarium", "vista città"]
    },
    {
        title: "Appartamento per Famiglia",
        description: "Spazioso appartamento con ampio soggiorno e cucina abitabile.",
        street: "Via Garibaldi 50",
        size: 110,
        bathrooms: 2,
        locals: 5,
        price: 300000,
        efficienza: "A",
        type: "VENDITA",
        images: ["image12.jpg", "image13.jpg"],
        lat: 41.9028,
        lon: 12.4964,
        tags: ["spazioso", "familiare", "cucina abitabile"]
    },
    {
        title: "Bilocale in Centro",
        description: "Bilocale accogliente, ideale per una coppia, situato in centro città.",
        street: "Via Dante 10",
        size: 60,
        bathrooms: 1,
        locals: 2,
        price: 150000,
        efficienza: "C",
        type: "VENDITA",
        images: ["image14.jpg"],
        lat: 45.4642,
        lon: 9.1900,
        tags: ["centrale", "accogliente", "coppia"]
    },
    {
        title: "Casale Rustico",
        description: "Casale rustico in campagna, ideale per chi cerca tranquillità.",
        street: "Via della Collina 32",
        size: 200,
        bathrooms: 3,
        locals: 6,
        price: 700000,
        efficienza: "B",
        type: "VENDITA",
        images: ["image15.jpg", "image16.jpg"],
        lat: 42.6304,
        lon: 12.4626,
        tags: ["rustico", "tranquillo", "campagna"]
    },
    {
        title: "Loft Industriale",
        description: "Loft con soffitti alti e finiture industriali, adatto per uso abitativo o ufficio.",
        street: "Via Milano 101",
        size: 180,
        bathrooms: 2,
        locals: 4,
        price: 600000,
        efficienza: "A",
        type: "VENDITA",
        images: ["image17.jpg", "image18.jpg"],
        lat: 45.4695,
        lon: 9.1901,
        tags: ["industriale", "loft", "spazioso"]
    },
    {
        title: "Appartamento con Giardino",
        description: "Appartamento al piano terra con giardino privato.",
        street: "Via dei Giardini 22",
        size: 85,
        bathrooms: 2,
        locals: 3,
        price: 200000,
        efficienza: "B",
        type: "VENDITA",
        images: ["image19.jpg", "image20.jpg"],
        lat: 45.0703,
        lon: 7.6869,
        tags: ["giardino", "piano terra", "spazioso"]
    },
    {
        title: "Attico con Terrazza Panoramica",
        description: "Attico con terrazza panoramica, perfetto per le cene estive.",
        street: "Piazza San Marco 2",
        size: 160,
        bathrooms: 3,
        locals: 5,
        price: 1200000,
        efficienza: "A",
        type: "VENDITA",
        images: ["image21.jpg", "image22.jpg"],
        lat: 45.4375,
        lon: 12.3358,
        tags: ["attico", "terrazza", "panoramico"]
    },
    {
        title: "Villa con Parco",
        description: "Villa con ampio parco privato, ideale per eventi e ricevimenti.",
        street: "Strada Parco 14",
        size: 500,
        bathrooms: 5,
        locals: 10,
        price: 2500000,
        efficienza: "A",
        type: "VENDITA",
        images: ["image23.jpg", "image24.jpg"],
        lat: 42.3601,
        lon: 71.0589,
        tags: ["villa", "parco", "lusso"]
    },
    {
        title: "Bilocale in Affitto",
        description: "Bilocale ben arredato in zona tranquilla, ideale per giovani coppie.",
        street: "Via Leonardo 12",
        size: 50,
        bathrooms: 1,
        locals: 2,
        price: 600,
        efficienza: "C",
        type: "AFFITTO",
        images: ["image25.jpg"],
        lat: 45.4333,
        lon: 9.1833,
        tags: ["coppia", "affitto", "arredato"]
    },
    {
        title: "Appartamento Ristrutturato",
        description: "Appartamento recentemente ristrutturato con materiali di alta qualità.",
        street: "Via Monti 15",
        size: 80,
        bathrooms: 1,
        locals: 3,
        price: 220000,
        efficienza: "A",
        type: "VENDITA",
        images: ["image26.jpg", "image27.jpg"],
        lat: 43.7721,
        lon: 11.2550,
        tags: ["ristrutturato", "alta qualità", "modernizzato"]
    },
    {
        title: "Loft Moderno",
        description: "Loft moderno con ampie finestre e open space.",
        street: "Via Torino 30",
        size: 110,
        bathrooms: 2,
        locals: 3,
        price: 350000,
        efficienza: "B",
        type: "VENDITA",
        images: ["image28.jpg", "image29.jpg"],
        lat: 45.0703,
        lon: 7.6869,
        tags: ["moderno", "open space", "spazioso"]
    },
    {
        title: "Casa con Cortile",
        description: "Casa indipendente con cortile privato e doppio ingresso.",
        street: "Viale dei Tigli 7",
        size: 180,
        bathrooms: 3,
        locals: 6,
        price: 600000,
        efficienza: "A",
        type: "VENDITA",
        images: ["image30.jpg", "image31.jpg"],
        lat: 44.4268,
        lon: 26.1025,
        tags: ["indipendente", "cortile", "spaziosa"]
    }
];
